import Navbar from "../components/Navbar";
import Head from "next/head";
import "../styles/globals.css";
import NextNProgress from "nextjs-progressbar";

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>James Mar del Plata</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" sizes="64x64" href="/images/logo.png" />
      </Head>
      <NextNProgress
        color="#29D"
        startPosition={0.3}
        stopDelayMs={200}
        height={3}
        showOnShallow={true}
        options={{ showSpinner: false }}
      />
      <Navbar />
      <Component {...pageProps} />
    </>
  );
}

export default MyApp;
