import Navbar from "../components/Navbar";
import Head from "next/head";
import "../styles/globals.css";

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>James Mar del Plata</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" sizes="64x64" href="/images/logo.png" />
      </Head>
      <Navbar />
      <Component {...pageProps} />
    </>
  );
}

export default MyApp;
